//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by IdmsMsn.rc
//
#define ID_BTN_DUPID_CHECK              3
#define ID_BTN_REG_RESET                4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CLIENTMESSENGER_DIALOG      102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_LOGIN                129
#define IDD_DIALOG_CHAT                 130
#define IDB_BITMAP_ONLINE               132
#define IDB_BITMAP_AWAY                 133
#define IDB_BITMAP_OffLine              134
#define IDR_MENU_MSGER                  135
#define IDD_DIALOG_NEW_COMPANION        136
#define IDD_DIALOG_NEW_USER             137
#define IDD_FILERECV_DLG                138
#define IDD_DLG_OPTION                  141
#define IDD_DLG_CHG_PWD                 143
#define IDD_DLG_NEW_LOGIN               144
#define IDB_BITMAP_USERID               146
#define IDB_BITMAP_PWD                  147
#define IDD_DIALOG_MSG                  148
#define IDB_BITMAP_GRPOPEN              150
#define IDB_BITMAP_GRPCLOSE             151
#define IDB_BITMAP_BLOCK                152
#define IDR_MENU_CONVERSATION           153
#define IDR_RIGHT_CLICK_MENU            154
#define IDR_RIGHT_GRP_MENU              155
#define IDR_TRAY_MENU                   156
#define IDD_DLG_GRP_MNG                 157
#define IDD_FILESEND_DLG                158
#define IDD_DIALOG_ALLMSG               159
#define IDD_DIALOG_VIEW_ALLMSG          160
#define IDI_ICON_SENDALLMSG_OK          163
#define IDR_MENU_VIEWALLMSG             164
#define IDD_DIALOG_MULTI_CHAT           165
#define IDD_DLG_WRITE_MSG               169
#define IDD_DLG_VIEW_SLIP_MDG           170
#define IDD_DLG_IT_COMP_MNG             171
#define IDR_MENU_ITCOMP                 172
#define IDB_BITMAP_ITCOMP               174
#define IDR_MENU_MY_STATUS              178
#define IDB_BITMAP_MYSTATUS_OVER        179
#define IDB_BITMAP_MYSTATUS_CLICK       180
#define IDB_TOPLEFT                     181
#define IDB_TOPRIGHT                    182
#define IDB_BOTTOMLEFT                  183
#define IDB_BOTTOMRIGHT                 184
#define IDB_BITMAP_ONLINE_B             185
#define IDB_BITMAP_SEC_BTN1_CLICKED     186
#define IDB_BITMAP_SEC_BTN2_CLICKED     187
#define IDB_BITMAP_SEC_BTN1_HIDE        188
#define IDB_BITMAP_SEC_BTN1_OVER        189
#define IDB_BITMAP_SEC_BTN2_HIDE        190
#define IDB_BITMAP_SEC_BTN2_OVER        191
#define IDB_BITMAP_SEC_BTN3_CLICKED     192
#define IDB_BITMAP_SEC_BTN3_HIDE        193
#define IDB_BITMAP_SEC_BTN3_OVER        194
#define IDB_BITMAP_BUSY_B               195
#define IDB_BITMAP_STATUS_BUSY          196
#define IDD_DLG_POLL_MAKE               197
#define IDD_DLG_POLL_ANSWER             198
#define IDD_DLG_POLL_LIST               199
#define IDI_ICON_SENDALLMSG_FAIL        202
#define IDI_ICON_SENDALLMSG_DEFAULT     203
#define IDB_BITMAP_ALLMSG_TREE          204
#define IDB_BITMAP_ALLMSG_STATUS        205
#define IDD_IDMSMSN_DIALOG              207
#define IDD_DLG_MODFY_REPLY             209
#define IDD_DLG_AUTO_APPEND_MSG         210
#define IDB_BITMAP_EMOTICON             211
#define IDD_DLG_EMOTICON_BASE           212
#define IDR_TOOLBAR_EMOTICON            216
#define IDI_ICON_CHK_ON                 224
#define IDI_ICON_CHK_OFF                225
#define IDI_ICON_PIN1                   228
#define IDI_ICON_PIN2                   229
#define IDC_BUTTON_EXIT                 1000
#define IDC_BTN_NEW_LOGIN               1000
#define ID_EB_REG_NAME                  1000
#define ID_BN_FIND                      1000
#define IDC_BUTTON_LOGIN                1001
#define ID_EB_USER_ID                   1001
#define IDC_RICHEDIT_CHAT               1002
#define ID_EB_PWD                       1002
#define IDC_BUTTON_SENDMSG              1003
#define ID_EB_CONFIRM_PWD               1003
#define IDC_EDIT_CHATMSG                1004
#define ID_EB_REG_SID                   1004
#define ID_EB_CHANGEPW_OLD              1004
#define IDC_BUTTON_TEST                 1005
#define IDC_SPLITTER1                   1005
#define IDC_CHAT_RICHEDIT               1006
#define ID_EB_TELOFC1                   1006
#define IDC_RICHEDIT21                  1007
#define IDC_TREECTRL                    1008
#define IDC_STATIC_DRAGBAR              1009
#define ID_CB_TEAM                      1009
#define IDC_IPADDRESS_NEWCOM            1010
#define ID_CB_GRADE                     1010
#define IDC_BUTTON_CONFIRM              1011
#define ID_ST_NAME                      1011
#define IDC_LIST_SEND                   1011
#define IDC_EDIT_LOGIN_ID               1012
#define ID_ST_ID                        1012
#define IDC_BTN_ADD                     1012
#define IDC_LIST_RECV                   1012
#define IDC_EDIT_PASSWD                 1013
#define ID_ST_PW1                       1013
#define IDC_STATIC_RECV_AMT             1013
#define IDC_STATIC_LOGIN_ID             1014
#define ID_ST_PW2                       1014
#define ID_SPRD_ID_LIST                 1014
#define IDC_SEND_BYTES_PROGRESS         1014
#define IDC_STATIC_PASSWD               1015
#define ID_ST_TEAM                      1015
#define ID_INFO_UPDATE                  1015
#define IDC_BTN_LOGIN_CANCEL            1016
#define ID_ST_GRADE                     1016
#define IDC_BUTTON_REGIST               1017
#define IDC_BTN_LOGIN_REGIST            1017
#define IDC_BTN_REG_USER_CANCEL         1018
#define ID_EB_NAME                      1018
#define IDC_STATIC_SENT_AMT             1018
#define IDC_EDIT_USER_ID                1019
#define ID_BN_CANCEL                    1019
#define IDC_STATIC_BYTE                 1019
#define IDC_STATIC_REG_USER_ID          1020
#define IDC_STATIC_FILE                 1020
#define IDC_EDIT_USER_PWD               1021
#define IDC_EDIT_COMP_ID                1021
#define IDC_STATIC_TOTAL                1021
#define IDC_STATIC_REG_USER_PWD         1022
#define IDC_BTN_CLOSE                   1022
#define IDC_EDIT_USER_CNFM_PWD          1023
#define IDC_BTN_OPT_OK                  1023
#define IDC_STATIC_REG_USER_CNFM_PWD    1024
#define IDC_BTN_OPT_CANCLE              1024
#define IDC_EDIT_USER_NICK_NAME         1025
#define IDC_EDIT_NICK                   1025
#define IDC_EDIT_NICK_NAME              1025
#define IDC_STATIC_REG_USER_NICK_NAME   1026
#define IDC_STATIC_NICK                 1026
#define IDC_EDIT_USER_REAL_NAME         1027
#define IDC_BTN_USER_FIND               1027
#define IDC_STATIC_REG_USER_REAL_NAME   1028
#define IDC_STATIC_MSG                  1028
#define ID_BTN_CHANGEPW_SAVE            1030
#define IDC_ED_ID                       1031
#define ID_BTN_CHANGEPW_RESET           1031
#define IDC_COMBO_GRP_SET               1031
#define IDC_ED_PWD                      1032
#define ID_EB_CHANGEPW_ID               1032
#define IDC_BTN_ADD_CLOSE               1032
#define IDC_BTN_LOGIN                   1033
#define ID_EB_CHANGEPW_NEW              1033
#define IDC_BTN_CANCEL                  1033
#define IDC_BTN_REG_USER                1034
#define ID_EB_CHANGEPW_CONFIRM          1034
#define IDC_EDIT_GRP_NAME               1034
#define IDC_BTN_CHG_PWD                 1035
#define ID_DM10CHANGEPW_ST_PW2          1035
#define IDC_STATIC_ROLE                 1035
#define ID_DM10CHANGEPW_ST_ID           1036
#define IDC_COMBO_CHG_GRP               1036
#define ID_DM10CHANGEPW_ST_PWOLD        1037
#define IDC_BTN_OK                      1037
#define ID_CB_COMPANY                   1038
#define ID_DM10CHANGEPW_ST_PW1          1038
#define ID_EB_TELOFC2                   1039
#define IDC_SEND_STATUS                 1039
#define ID_EB_TELOFC3                   1040
#define IDC_EDIT_SEND_FILE              1040
#define ID_EB_TEL_BRANCH                1041
#define IDC_SEND_PROGRESS               1041
#define ID_EB_TELHP1                    1042
#define IDC_BTN_FILE_SEND_CANCEL        1042
#define ID_EB_TELHP2                    1043
#define ID_BN_SEARCH                    1043
#define ID_EB_TELHP3                    1044
#define IDC_LIST_ALLMSG_STATUS          1044
#define ID_ST_JUMIN                     1045
#define ID_EB_USERID                    1045
#define ID_ST_YESNO                     1046
#define IDC_EDIT_ALLMSG                 1046
#define ID_EB_USERNAME                  1046
#define IDC_CHECK_RESEND                1047
#define IDC_BTN_SENDALLMSG              1048
#define IDC_BTN_ALLMSG_OK               1049
#define IDC_REDIT_VIEW_ALLMSG           1050
#define IDC_CHK_OFFLINE_SEND            1050
#define IDC_BTN_VIEW_ALLMSG_OK          1051
#define IDC_REDIT_MULTICHAT             1052
#define IDC_LIST_MULTICHAT              1053
#define IDC_RECEIVE_PROGRESS            1054
#define IDC_EDIT_MULTICHATMSG           1054
#define IDC_BTN_SEND_MULTICHAT_MSG      1055
#define IDC_RECV_BYTES_PROGRESS         1055
#define IDC_LIST_LOGIN_ID               1057
#define IDC_STATUS_STATIC               1058
#define IDC_CHK_EXIT_MULTICHAT          1058
#define IDC_SPEED_STATIC                1059
#define IDC_GRP_MC                      1059
#define IDC_TIME_STATIC                 1060
#define IDC_COMBO_AWAY_SEC              1060
#define IDC_FILESIZE_STATIC             1061
#define IDC_EDIT_WRITE_MSG              1061
#define IDC_STATIC_MSGTO                1062
#define IDC_BTN_WRITE_MSG               1063
#define IDC_BTN_WRITE_MSG_CNCL          1064
#define IDC_STATIC_MSG_FROM             1065
#define ID_BN_SAVE                      1066
#define IDC_BTN_SLIP_MSG_CLOSE          1067
#define IDC_REDIT_SLIP_MSG              1068
#define IDC_EDIT_URL                    1070
#define IDC_EDIT_DESC                   1071
#define IDC_BTN_ADD_MODIFY              1072
#define IDC_CHK_AUTO_LOGIN              1074
#define IDC_CHK_ALWAYSONTOP             1075
#define IDC_BTN_MY_STATUS               1075
#define IDC_STATIC_MY_NICK              1076
#define IDC_CHK_DOWN_FOLDER             1076
#define IDC_BTN_SEC1                    1077
#define IDC_CHK_USE_SOUND               1077
#define IDC_BTN_SEC2                    1078
#define IDC_SPLITTER                    1078
#define IDC_CHK_LOG_FOLDER              1078
#define IDC_BTN_SEC3                    1079
#define IDC_EDIT_ASK_WHAT               1079
#define IDC_EDIT_SEL1                   1080
#define IDC_EDIT_SEL2                   1081
#define IDC_EDIT_SEL3                   1082
#define IDC_EDIT_SEL4                   1083
#define IDC_BTN_POLL                    1086
#define IDC_LIST_POLL_TARGET            1087
#define IDC_RADIO_SEL1                  1089
#define IDC_RADIO_SEL2                  1090
#define IDC_RADIO_SEL3                  1091
#define IDC_RADIO_SEL4                  1092
#define IDC_BTN_NO_POLL                 1093
#define IDC_BTN_POLL_SUBMIT             1094
#define IDC_STATIC_POLL_BY              1096
#define IDC_LIST_POLL                   1097
#define IDC_STATIC_LOGIN_MSG            1099
#define IDC_BTN_FILE_CONFIRM            1101
#define IDC_BTN_FILE_NOT_CONFIRM        1102
#define IDC_EDIT_CONFIRM                1103
#define ID_RB_DIARY_YES                 1104
#define IDC_BTN_OPEN_FILE_FOLDER        1104
#define ID_RB_DIARY_NO                  1105
#define IDC_RADIO_SELTEAM               1105
#define IDC_RADIO_SELID                 1106
#define IDC_BUTTON_UPDATE               1107
#define IDC_CHK_SELECT_ALL              1108
#define IDC_STATIC_ALLMSG_INFO          1109
#define IDC_TREE_ALL_MSG                1110
#define IDC_BUTTON_EXPANDALL            1111
#define IDC_TREE_USER_LISTALL           1113
#define IDC_RADIO_SEARCH                1114
#define IDC_RADIO_LISTALL               1115
#define IDC_STATIC_DOWN_FOLER           1117
#define IDC_BTN_DOWN_FOLDER             1118
#define IDC_STATIC_SOUND_PATH           1119
#define IDC_BTN_SELECT_SOUND            1120
#define IDC_COMBO_REPLY                 1121
#define IDC_BTN_PLAY_SOUND              1121
#define IDC_BTN_ADD_LIST                1122
#define IDC_BTN_STOP_SOUND              1122
#define IDC_STATIC_REPLY                1123
#define IDC_STATIC_LOG_FOLER            1123
#define IDC_BTN_LOG_FOLDER              1124
#define IDC_CHECK_SELECT_SEND           1125
#define IDC_EDIT_REPLY0                 1126
#define IDC_CHECK_ALWAYS_TOP            1126
#define IDC_BTN_REPLY_OK                1127
#define IDC_CHECK_SEP_LINE              1127
#define IDC_BTN_REPLY_CANCEL            1128
#define IDC_STATIC_GRP1                 1128
#define IDC_EDIT_REPLY1                 1129
#define IDC_STATIC_GRP2                 1129
#define IDC_EDIT_REPLY2                 1130
#define IDC_BTN_SEND_FILE               1130
#define IDC_EDIT_REPLY3                 1131
#define IDC_BTN_SAVE_FILE               1131
#define IDC_BTN_AUTOAPPENDMSG_CANCEL    1131
#define IDC_EDIT_REPLY4                 1132
#define IDC_BTN_BUDDY_MSG               1132
#define IDC_BTN_AUTOAPPENDMSG_OK        1132
#define IDC_EDIT_REPLY5                 1133
#define IDC_BTN_CHG_SEPLINE             1133
#define IDC_EDIT_AUTO_APPEND_MSG        1133
#define IDC_EDIT_REPLY6                 1134
#define IDC_BTN_EMOTICON                1134
#define IDC_EDIT_REPLY7                 1135
#define IDC_RICHEDIT_SENDMSG            1135
#define IDC_STATIC_GRP3                 1135
#define IDC_EDIT_REPLY8                 1136
#define IDC_STATIC_GRP4                 1136
#define IDC_EDIT_REPLY9                 1137
#define IDC_COLOURPICKER_ME             1137
#define IDC_COLOURPICKER_BUDDY          1138
#define IDC_BUTTON_FONT                 1139
#define IDC_RICHEDIT_EXAMPLE            1140
#define IDC_COLOURPICKER_BG             1141
#define IDC_BTN_OPEN_CHAT               1141
#define ID_CLOSE_MSGER                  32771
#define IDC_ADDPARTNER                  32772
#define IDC_RUNIDMS                     32773
#define ID_BROADCAST_MSG                32774
#define ID_RESERVED_MSG                 32775
#define ID_VIEW_ALLMSG_HIST             32775
#define ID_CHANGESCREENNAME             32776
#define ID_TOOLS_OPTIONS                32777
#define ID_VIEW_ALARM_MSG               32778
#define IDC_FILESAVE                    32779
#define IDC_CONV_CLOSE                  32780
#define IDC_COLOR_ME                    32781
#define IDC_COLOR_COMP                  32782
#define IDC_COLOR_BG                    32783
#define IDC_FONT                        32784
#define IDC_ALWAYS_ONTOP                32785
#define ID_VIEW_CHAT_HIST               32786
#define ID_TOOLS_OPTION                 32787
#define ID_TOOLS_ABOUT                  32788
#define IDRCLICK_SENDFILE               32789
#define IDRCLICK_DELETE                 32790
#define IDRCLICK_ALLMSG                 32791
#define IDRCLICK_MULTICHAT              32792
#define IDRCLICK_GRP_CHG                32793
#define ID_GRP_MNG_ADD                  32794
#define ID_GRP_MNG_MODIFY               32795
#define ID_GRP_MNG_ADDCOMP              32796
#define ID_GRP_MNG_ALLMSG               32797
#define ID_GRP_MNG_SENDFILE             32798
#define ID_TRAYMENU_RESTORE             32799
#define IDRTRAYMENU_QUIT                32800
#define ID_GRP_MNG_DEL                  32801
#define IDC_ALLMSG_FILESAVE             32802
#define IDC_ALLMSG_CLOSE                32803
#define IDC_ALLMSG_HIST                 32804
#define ID_RUN_IDMS                     32805
#define IDRCLICK_WRITE_MSG              32807
#define ID_VIEW_SLIPMSG_LOG             32808
#define ID_GRP_MNG_ADD_ITCOMP           32809
#define IDRCLICK_ITCOMP_DEL             32810
#define IDRCLICK_ITCOMP_MODIFY          32811
#define IDRCLICK_ITCOMP_ADD             32812
#define IDM_MYSTATUS_ONLINE             32814
#define IDM_MYSTATUS_BUSY               32815
#define ID_TRAYMENU_MDB                 32816
#define ID_TRAYMENU_SOCKTEST            32817
#define ID_TRAYMENU_TUXTEST             32818
#define ID_TRAYMENU_IDMS                32819
#define ID_RUN_MDB                      32820
#define ID_RUN_SOCK_TEST                32821
#define ID_RUN_TUX_TEST                 32822
#define ID_RUN_RS_BOARD                 32823
#define ID_BUTTON32824                  32824
#define ID_BUTTON32825                  32825
#define ID_BUTTON32826                  32826
#define ID_BUTTON32827                  32827
#define ID_BUTTON32828                  32828
#define ID_BUTTON32829                  32829
#define ID_BUTTON32830                  32830
#define ID_BUTTON32831                  32831
#define ID_BUTTON32832                  32832
#define ID_BUTTON32833                  32833
#define ID_BUTTON32834                  32834
#define ID_BUTTON32835                  32835
#define ID_BUTTON32836                  32836
#define ID_BUTTON32837                  32837
#define ID_BUTTON32838                  32838
#define ID_BUTTON32839                  32839
#define ID_BUTTON32840                  32840
#define ID_BUTTON32841                  32841
#define ID_BUTTON32842                  32842
#define ID_BUTTON32843                  32843
#define ID_BUTTON32844                  32844
#define ID_BUTTON32845                  32845
#define ID_BUTTON32846                  32846
#define ID_BUTTON32847                  32847
#define ID_BUTTON32848                  32848
#define ID_BUTTON32849                  32849
#define ID_BUTTON32850                  32850
#define ID_BUTTON32851                  32851
#define ID_BUTTON32852                  32852
#define ID_BUTTON32853                  32853
#define ID_BUTTON32854                  32854
#define ID_BUTTON32855                  32855
#define ID_BUTTON32856                  32856
#define ID_BUTTON32857                  32857
#define ID_BUTTON32858                  32858
#define ID_BUTTON32859                  32859
#define ID_BUTTON32860                  32860
#define ID_BUTTON32861                  32861
#define ID_BUTTON32862                  32862
#define IDM_MYSTATUS_AWAY               32863
#define IDM_OPTION                      32864

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        230
#define _APS_NEXT_COMMAND_VALUE         32865
#define _APS_NEXT_CONTROL_VALUE         1142
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
